### PR TITLE
Added mobile version of logo

### PR DESCRIPTION
**Pull request by Xenosb**

### CODE REVIEW

**Comment by monorkin** [comment]
Is there code to load this image?

**Comment by Xenosb** [comment]
Nay, Matthieu told me to the push image on git. I supposed that code is
already there.
Check with him.

**Comment by mkrpan** [comment]
aj ju pushaj ponovo. sad sam napravio pull reqeust na code koji učitava sliku na mobitelima

**Comment by Xenosb** [comment]
@Stankec should approve this pull request. Since there are no conflicts on the upstream, merge should be successful.

**Pull request merged**
